### ISSUE TITLE
Could I ask data?

### ISSUE THREAD

**Issue by vm-elliot** [CHDyshli/PavementCrackDetection#2]
Hello sir is there data with traditional label which said in your paper?
![1_10](https://github.com/CHDyshli/PavementCrackDetection/assets/101856249/65cc523b-fbfa-465e-a9fb-5c8f4d953f52)

**Comment by CHDyshli** [comment]
We didn't do traditional labeling. For this image, a traditional labeling may need to cover the entire image, which we feel is not reasonable or accurate enough.

**Comment by vm-elliot** [comment]
Thank you sir
